---
kind: Service
apiVersion: v1
metadata:
  name: testflight-api
  labels:
    app: testflight-service
spec:
  type: NodePort
  selector:
    app: testflight
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000

